//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItDeclarationForm
    {
        public int ItDeclarationID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> ItDeclarationYear { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string PanNo { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string AddressState { get; set; }
        public string AddressCountry { get; set; }
        public string AddressZip { get; set; }
        public Nullable<int> PurchaseOfNSC { get; set; }
        public Nullable<int> InsurancePremium { get; set; }
        public Nullable<int> PPF { get; set; }
        public Nullable<int> HousingLoan { get; set; }
        public string ChildrenTutionFee { get; set; }
        public Nullable<int> MutualfundOrUti { get; set; }
        public Nullable<int> BondsOfNabard { get; set; }
        public Nullable<int> InterestOnNSC { get; set; }
        public Nullable<int> FDR { get; set; }
        public Nullable<int> ULIPofUTI { get; set; }
        public Nullable<int> PF { get; set; }
        public Nullable<int> MediclaimPremium { get; set; }
        public Nullable<int> HomeLoan { get; set; }
        public string HLAddressLine1 { get; set; }
        public string HLAddressLine2 { get; set; }
        public string HLAddressLine3 { get; set; }
        public string HLAddressState { get; set; }
        public string HLAddressCountry { get; set; }
        public string HLAddressZip { get; set; }
        public Nullable<int> HomeRent { get; set; }
        public string HRAddressLine11 { get; set; }
        public string HRAddressLine21 { get; set; }
        public string HRAddressLine31 { get; set; }
        public string HRAddressState1 { get; set; }
        public string HRAddressCountry1 { get; set; }
        public string HRAddressZip1 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string AddressCity { get; set; }
        public string HLAddressCity { get; set; }
        public string HRAddressCity { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> NPS { get; set; }
        public Nullable<int> NSC { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
